In [17]:
import numpy as np

def a():
    return 1, 2, 3

In [30]:
type(1)

int

In [56]:
run q3_word2vec.py


Testing normalizeRows...
[[ 0.6         0.8       ]
 [ 0.4472136   0.89442719]]

==== Gradient check for skip-gram ====
first
[[-0.96735714 -0.02182641  0.25247529]
 [ 0.73663029 -0.48088687 -0.47552459]
 [-0.27323645  0.12538062  0.95374082]
 [-0.56713774 -0.27178229 -0.77748902]
 [-0.59609459  0.7795666   0.19221644]
 [-0.6831809  -0.04200519  0.72904007]
 [ 0.18289107  0.76098587 -0.62245591]
 [-0.61517874  0.5147624  -0.59713884]
 [-0.33867074 -0.80966534 -0.47931635]
 [-0.52629529 -0.78190408  0.33412466]]
Gradient check failed.
First gradient error found at index (0, 0)
Your gradient: 0.321120 	 Numerical gradient: -0.087147
second


ValueError: cannot reshape array of size 121 into shape (1,11)