In [6]:
import numpy as np

In [11]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
np.square(a)

array([[ 0,  1,  4],
       [ 9, 16, 25]], dtype=int32)

In [30]:
from q3_word2vec import normalizeRows
from q3_word2vec import test_normalize_rows

In [33]:
x = np.array([4,5,6])

In [37]:
a = np.array([1,2,3]).reshape(3,1)
b = np.array([4,5,6]).reshape(1,3)

In [44]:
a = np.array([1,2,3,4])
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [45]:
a


array([1, 2, 3, 4])